-- Supabase Schema Initialization for ReptiTrack
-- Run this in your Supabase project's SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. CLEANUP (Optional - only if resetting)
-- DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
-- DROP FUNCTION IF EXISTS public.handle_new_user;
-- DROP FUNCTION IF EXISTS public.create_shipment_with_receiver;
-- DROP TABLE IF EXISTS public.profiles;
-- DROP TABLE IF EXISTS public.payment;
-- DROP TABLE IF EXISTS public.tracking;
-- DROP TABLE IF EXISTS public.shipment;
-- DROP TABLE IF EXISTS public.service_type;
-- DROP TABLE IF EXISTS public.receiver;
-- DROP TABLE IF EXISTS public.receiver_pincode;
-- DROP TABLE IF EXISTS public.customer;
-- DROP TABLE IF EXISTS public.customer_pincode;
-- DROP TABLE IF EXISTS public.courier;

-- 2. CREATE TABLES

CREATE TABLE public.courier (
    COURIERID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100),
    PHONE VARCHAR(20)
);

CREATE TABLE public.customer_pincode (
    PINCODE INT PRIMARY KEY,
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);

CREATE TABLE public.customer (
    CUSTOMERID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    REGISTRATIONDATE DATE,
    STATUS VARCHAR(20),
    STREET VARCHAR(100),
    PINCODE INT REFERENCES public.customer_pincode(PINCODE) ON DELETE SET NULL
);

CREATE TABLE public.receiver_pincode (
    PINCODE INT PRIMARY KEY,
    CITY VARCHAR(50),
    STATE VARCHAR(50)
);

CREATE TABLE public.receiver (
    RECEIVERID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    STREET VARCHAR(100),
    PINCODE INT REFERENCES public.receiver_pincode(PINCODE) ON DELETE SET NULL
);

CREATE TABLE public.service_type (
    SERVICETYPEID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SERVICENAME VARCHAR(50),
    DELIVERYDAYS INT,
    BASERATE DECIMAL(10,2)
);

CREATE TABLE public.shipment (
    SHIPMENTID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOOKINGDATE TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    CURRENTSTATUS VARCHAR(30) DEFAULT 'Booked',
    PRIORITY VARCHAR(20) DEFAULT 'Normal',
    TOTALCOST DECIMAL(10,2) DEFAULT 0.00,
    CUSTOMERID INT REFERENCES public.customer(CUSTOMERID) ON DELETE CASCADE,
    RECEIVERID INT REFERENCES public.receiver(RECEIVERID) ON DELETE SET NULL,
    COURIERID INT REFERENCES public.courier(COURIERID) ON DELETE SET NULL
);

CREATE TABLE public.tracking (
    TRACKINGID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    STATUS VARCHAR(30) DEFAULT 'Booked',
    LOCATION VARCHAR(100),
    TIMESTAMP TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    SHIPMENTID INT REFERENCES public.shipment(SHIPMENTID) ON DELETE CASCADE
);

CREATE TABLE public.payment (
    PAYMENTID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PAYMENTDATE DATE,
    PAYMENTMETHOD VARCHAR(30) DEFAULT 'Not Set',
    PAYMENTSTATUS VARCHAR(20) DEFAULT 'Pending',
    TRANSACTIONID VARCHAR(50),
    SHIPMENTID INT REFERENCES public.shipment(SHIPMENTID) ON DELETE CASCADE
);

-- User Profiles to map authenticated users to their customer profiles and roles
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(20) DEFAULT 'user',
    customer_id INT REFERENCES public.customer(CUSTOMERID) ON DELETE SET NULL
);

-- 3. INSERT SEED DATA FOR SERVICE TYPES & COURIERS
INSERT INTO public.service_type (SERVICENAME, DELIVERYDAYS, BASERATE) VALUES
('Standard', 5, 50.00),
('Express', 2, 100.00),
('Overnight', 1, 200.00)
ON CONFLICT DO NOTHING;

INSERT INTO public.courier (NAME, PHONE) VALUES
('Fast Delivery Inc', '+919988776655'),
('Swift Express Services', '+919922334455'),
('Blue Dart Logistics', '+919876543210')
ON CONFLICT DO NOTHING;

-- 4. SIGNUP TRIGGER FUNCTION (Automatic customer/profile creation)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    new_customer_id INT;
    user_fullname VARCHAR(100);
    user_role VARCHAR(20) := 'user';
BEGIN
    -- Determine role (the first user is promoted to admin for convenience, or check metadata)
    IF NOT EXISTS (SELECT 1 FROM public.profiles) THEN
        user_role := 'admin';
    END IF;

    -- Extract full name from user metadata, fallback to email name if not present
    user_fullname := COALESCE(new.raw_user_meta_data->>'full_name', SPLIT_PART(new.email, '@', 1));

    -- Insert into customer table
    INSERT INTO public.customer (NAME, EMAIL, REGISTRATIONDATE, STATUS)
    VALUES (user_fullname, new.email, CURRENT_DATE, 'Active')
    RETURNING CUSTOMERID INTO new_customer_id;

    -- Insert into profiles table
    INSERT INTO public.profiles (id, email, role, customer_id)
    VALUES (new.id, new.email, user_role, new_customer_id);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute handle_new_user on auth.users insert
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 5. SHIPMENT TRANSACTION FUNCTION (RPC)
CREATE OR REPLACE FUNCTION public.create_shipment_with_receiver(
    p_customer_id INT,
    p_sender_street VARCHAR(100),
    p_sender_pincode INT,
    p_sender_city VARCHAR(50),
    p_sender_state VARCHAR(50),
    p_receiver_name VARCHAR(100),
    p_receiver_email VARCHAR(100),
    p_receiver_street VARCHAR(100),
    p_receiver_pincode INT,
    p_receiver_city VARCHAR(50),
    p_receiver_state VARCHAR(50),
    p_service_type_id INT,
    p_priority VARCHAR(20)
)
RETURNS INT AS $$
DECLARE
    v_receiver_id INT;
    v_base_rate DECIMAL(10,2);
    v_priority_multiplier DECIMAL(3,2) := 1.0;
    v_total_cost DECIMAL(10,2);
    v_shipment_id INT;
    v_booking_date TIMESTAMP WITH TIME ZONE := NOW();
BEGIN
    -- 1. Insert/Update Sender Pincode
    IF p_sender_pincode IS NOT NULL THEN
        INSERT INTO public.customer_pincode (PINCODE, CITY, STATE)
        VALUES (p_sender_pincode, COALESCE(p_sender_city, 'Unknown'), COALESCE(p_sender_state, 'Unknown'))
        ON CONFLICT (PINCODE) DO UPDATE
        SET CITY = CASE WHEN EXCLUDED.CITY <> 'Unknown' THEN EXCLUDED.CITY ELSE customer_pincode.CITY END,
            STATE = CASE WHEN EXCLUDED.STATE <> 'Unknown' THEN EXCLUDED.STATE ELSE customer_pincode.STATE END;

        -- Update customer's address
        UPDATE public.customer
        SET STREET = p_sender_street, PINCODE = p_sender_pincode
        WHERE CUSTOMERID = p_customer_id;
    END IF;

    -- 2. Insert/Update Receiver Pincode
    IF p_receiver_pincode IS NOT NULL THEN
        INSERT INTO public.receiver_pincode (PINCODE, CITY, STATE)
        VALUES (p_receiver_pincode, COALESCE(p_receiver_city, 'Unknown'), COALESCE(p_receiver_state, 'Unknown'))
        ON CONFLICT (PINCODE) DO NOTHING;
    END IF;

    -- 3. Match or Create Receiver
    SELECT RECEIVERID INTO v_receiver_id FROM public.receiver WHERE EMAIL = p_receiver_email LIMIT 1;
    IF v_receiver_id IS NOT NULL THEN
        UPDATE public.receiver
        SET STREET = p_receiver_street, PINCODE = p_receiver_pincode
        WHERE RECEIVERID = v_receiver_id;
    ELSE
        INSERT INTO public.receiver (NAME, EMAIL, STREET, PINCODE)
        VALUES (p_receiver_name, p_receiver_email, p_receiver_street, p_receiver_pincode)
        RETURNING RECEIVERID INTO v_receiver_id;
    END IF;

    -- 4. Get service type details
    SELECT BASERATE INTO v_base_rate
    FROM public.service_type WHERE SERVICETYPEID = p_service_type_id;
    IF v_base_rate IS NULL THEN
        v_base_rate := 50.00;
    END IF;

    -- 5. Priority cost calculation
    IF p_priority = 'High' THEN
        v_priority_multiplier := 1.5;
    ELSIF p_priority = 'Urgent' THEN
        v_priority_multiplier := 2.0;
    END IF;
    v_total_cost := v_base_rate * v_priority_multiplier;

    -- 6. Insert shipment
    INSERT INTO public.shipment (BOOKINGDATE, CURRENTSTATUS, PRIORITY, TOTALCOST, CUSTOMERID, RECEIVERID)
    VALUES (v_booking_date, 'Booked', p_priority, v_total_cost, p_customer_id, v_receiver_id)
    RETURNING SHIPMENTID INTO v_shipment_id;

    -- 7. Insert initial tracking history
    INSERT INTO public.tracking (SHIPMENTID, STATUS, LOCATION, TIMESTAMP)
    VALUES (v_shipment_id, 'Booked', COALESCE(p_sender_city, 'Origin') || ' Warehouse', v_booking_date);

    -- 8. Insert initial payment record
    INSERT INTO public.payment (SHIPMENTID, PAYMENTSTATUS, PAYMENTDATE, PAYMENTMETHOD, TRANSACTIONID)
    VALUES (v_shipment_id, 'Pending', v_booking_date::DATE, 'Not Set', 'TXN' || v_shipment_id || FLOOR(RANDOM() * 9000 + 1000)::TEXT);

    RETURN v_shipment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 6. ROW LEVEL SECURITY (RLS) POLICIES
-- Enable RLS on core tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receiver ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to update their own profiles" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Shipment Policies
CREATE POLICY "Allow admins full access to shipments" ON public.shipment FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);
CREATE POLICY "Allow users to view their own shipments" ON public.shipment FOR SELECT USING (
    CUSTOMERID = (SELECT customer_id FROM public.profiles WHERE id = auth.uid())
);
CREATE POLICY "Allow users to insert their own shipments" ON public.shipment FOR INSERT WITH CHECK (
    CUSTOMERID = (SELECT customer_id FROM public.profiles WHERE id = auth.uid())
);

-- Tracking Policies
CREATE POLICY "Allow anyone to read tracking details" ON public.tracking FOR SELECT USING (true);
CREATE POLICY "Allow admins to update tracking details" ON public.tracking FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);

-- Payment Policies
CREATE POLICY "Allow admins full access to payments" ON public.payment FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);
CREATE POLICY "Allow users to view their own payments" ON public.payment FOR SELECT USING (
    SHIPMENTID IN (
        SELECT SHIPMENTID FROM public.shipment
        WHERE CUSTOMERID = (SELECT customer_id FROM public.profiles WHERE id = auth.uid())
    )
);

-- Customer Policies
CREATE POLICY "Allow admins full access to customers" ON public.customer FOR ALL USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin'
);
CREATE POLICY "Allow users to view/update their own customer profiles" ON public.customer FOR ALL USING (
    CUSTOMERID = (SELECT customer_id FROM public.profiles WHERE id = auth.uid())
);
